name: Node.js CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Check Node.js Version
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './package-lock.json'

    - name: Install Dependencies
      run: npm ci

    - name: Install PM2 Globally
      run: npm i -g pm2

    - name: Start Next.js Application
      run: |
        pm2 delete all || true
        pm2 start "npm run dev" --name "Anime"
